### ISSUE TITLE
bypass function does not work with supertest

### ISSUE THREAD

**Issue by arenoir** [kettanaito/msw#1870]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.9.0

### Reproduction repository

https://github.com/arenoir/msw-bypass-node-example

### Reproduction steps

1. setup a msw server with a [handler](https://github.com/arenoir/msw-bypass-node-example/blob/main/tests/helpers/mock-server.js#L13) using the bypass function.
2. Use supertest to make a [request](https://github.com/arenoir/msw-bypass-node-example/blob/main/server.test.js#L29) against an express application.
3. See the [error](https://github.com/arenoir/msw-bypass-node-example/actions/runs/6909137720/job/18799872654#step:5:39).

### Current behavior

The bypass function fails.

### Expected behavior

The bypass function should make a request.

**Comment by kettanaito** [comment]
Hey, @arenoir! Thanks for reporting this.

One thing, it doesn't seem like you're using the `bypass` API [correctly](https://mswjs.io/docs/api/bypass#usage). Its a wrapper that produces the _bypassed `Request`_ but you still need to make the actual fetch. 

In your code, make this change:

```diff
// Fetch the original response from the GitHub API.
-const gist = await bypass(request).then((response) => response.json())
+const gist = await fetch(bypass(request)).then((response) => response.json())
```

This will trigger a request for the resource and give you back the original JSON response. Let me know if that helps.

**Comment by kettanaito** [comment]
I also apologize for the misleading docs that featured the wrong usage of the `bypass` API. 

I've updated the docs to make sure they feature the correct usage of the function. This includes the following pages:

- [Comparison](https://mswjs.io/docs/comparison)
- [`bypass` API](https://mswjs.io/docs/api/bypass)
- [Response patching recipe](https://mswjs.io/docs/recipes/response-patching)

Thanks for helping discover this!

**Comment by arenoir** [comment]
Hi @kettanaito thanks for taking a look.  I have tried using the bypass option every way I have seen it used in the documentation with no success. I have updated the example application [handler](https://github.com/arenoir/msw-bypass-node-example/blob/main/tests/helpers/mock-server.js#L20) and the bypass function is still not [working](https://github.com/arenoir/msw-bypass-node-example/actions/runs/6933317484/job/18859228281#step:5:20).  

Would you double check that this is not a bug?

**Comment by arenoir** [comment]
This is the error that the fetch function throws when passing it a bypass(request). 

```
TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at new Request (file:///Users/aaronrenoir/Workspace/arenoir/msw-bypass-node-example/node_modules/node-fetch/src/request.js:55:16)
    at file:///Users/aaronrenoir/Workspace/arenoir/msw-bypass-node-example/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at Proxy.fetch (file:///Users/aaronrenoir/Workspace/arenoir/msw-bypass-node-example/node_modules/node-fetch/src/index.js:49:9)
    at /Users/aaronrenoir/Workspace/arenoir/msw-bypass-node-example/tests/helpers/mock-server.js:20:42
    at HttpHandler.<anonymous> (file:///Users/aaronrenoir/Workspace/arenoir/msw-bypass-node-example/node_modules/msw/lib/core/handlers/RequestHandler.mjs:128:55)
    at Generator.next (<anonymous>)
    at file:///Users/aaronrenoir/Workspace/arenoir/msw-bypass-node-example/node_modules/msw/lib/core/handlers/RequestHandler.mjs:37:61
    at new Promise (<anonymous>) {
  code: 'ERR_INVALID_URL',
  input: '[object Request]'
}
```

**Comment by arenoir** [comment]
Hi @kettanaito, would you re-open this issue?  The bypass function is not working as intended and I suspect it is related to how supertest makes requests to the express application.  For example to make the initial application request we have to add a MSW passthrough [handler](https://github.com/arenoir/msw-bypass-node-example/blob/main/tests/helpers/mock-server.js#L8).   It seems to me that there may be some incompatibility with supertest?   Best.

**Comment by mattcosta7** [comment]
> Hi [@kettanaito](https://github.com/kettanaito), would you re-open this issue? The bypass function is not working as intended and I suspect it is related to how supertest makes requests to the express application. For example to make the initial application request we have to add a MSW passthrough [handler](https://github.com/arenoir/msw-bypass-node-example/blob/main/tests/helpers/mock-server.js#L8). It seems to me that there may be some incompatibility with supertest? Best.

I've run this in node 18 and 20 from your repro, and removing `import fetch from 'node-fetch'` in your mock-server.js as well as the try/catch around the call to bypass makes all of the tests green without other changes as far as I can tell.

So it appears to be working properly, although `node-fetch` in a handler is likely causing a weird mismatch between undici's fetch implementation and its own

**Comment by mattcosta7** [comment]
@arenoir I opened a PR to your repro with my changes - https://github.com/arenoir/msw-bypass-node-example/pull/1

**Comment by arenoir** [comment]
@mattcosta7 thanks for taking a look.  Wow it is working but how.  Is MSW setting a global?  That is very strange,  where is `fetch` being imported?    This will not pass our linting but I guess we can add an exception.  Should we import the 'undici' version of fetch from MSW?  If so that should probably be added to the documentation.   Any insight into what is going on would be appreciated.

**Comment by arenoir** [comment]
@mattcosta7 okay I see that fetch is a global in node since version [18](https://nodejs.org/en/blog/release/v18.0.0/) that would explain it. 

Thank you so much for the help.
