### ISSUE TITLE
TypeError: Cannot set property headers of #<_Request> which has only a getter

### ISSUE THREAD

**Issue by stevensacks** [kettanaito/msw#2290]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.17.0

### Reproduction repository

https://github.com/gaia-react/remix

### Reproduction steps

1. Run `npx create-remix@latest --template gaia-react/remix`
2. `npm install msw@2.4.8` (it's currently using 2.4.2 which is the last working version)
3. `npm run dev` to launch Remix server
4. Click on "Auth Example"
5. Type in the password `passw0rd` (zero for o) and click the Login button
6. TypeError occurs - MSW handler does not get called

### Current behavior

I'm using remix-auth to make the call to the login endpoint, but it doesn't make it to the defined MSW handler.

If you need the console log of the error to show up in the terminal process, add it [here after line 21](https://github.com/gaia-react/remix/blob/main/app/routes/_auth%2B/login.tsx#L21).

```
TypeError: Cannot set property headers of #<_Request> which has only a getter
      at Object.construct (file:///Users/stevensacks/Development/gaia/framework/remix/node_modules/@mswjs/interceptors/lib/node/chunk-RWGRRMVU.mjs:217:27)
      at Authenticator.authenticate (/Users/stevensacks/Development/gaia/framework/remix/node_modules/remix-auth/build/authenticator.js:68:41)
```

### Expected behavior

Expect the API call to go through to the MSW handler, as it does in version 2.4.2.

**Comment by hugotiburtino** [comment]
Same [here](https://github.com/serlo/cloudflare-worker/pull/878). See error in [CI](https://github.com/serlo/cloudflare-worker/actions/runs/10892974246/job/30226971649)

To reproduce, just clone the [repo](https://github.com/serlo/cloudflare-worker), check the branch `dependabot/npm_and_yarn/msw-2.4.7` out, install with `yarn` and run `yarn test`

**Comment by kettanaito** [comment]
@stevensacks, can you please point me to what exact request handler you expect to be called?

**Comment by kettanaito** [comment]
I believe I tracked down the issue. Opened a fix at https://github.com/mswjs/interceptors/pull/640. Will propagate to MSW soon. 

I'd love to know more details on the expected result. The error is not thrown anymore in your code, but nothing happens on the page. I can see the 302 response arriving as `error` in your auth logic. That seems to be related to your application (maybe that's intentional?).

**Comment by stevensacks** [comment]
That is odd. Login was working before with the msw handler (inside the test folder) as written. I’ll look into it asap.

**Comment by stevensacks** [comment]
Seems to be a bug in remix-auth. It's not storing the session correctly.

Login succeeds
Redirects to /profile
Profile loader authenticator.isAuthenticated fails
Redirects to /login

From the user side, it appears to never leave the login page.

**Comment by kettanaito** [comment]
We did release some fixes around redirects in MSW, but those are suppose to follow redirects correctly (that was never done before). They are also relevant to _fetch_ only. In your case, you are using `ClientRequest` in Node.js, so you can disregard this message. 

I believe the underlying issue is fixed. We didn't cover one `Request` constructor scenario when recording raw headers. I will propagate the fix to MSW, and you will have no errors in your auth logic.

**Comment by stevensacks** [comment]
The reason it wasn't redirecting to /profile after login was a mistake in my code. remix-auth's authenticator throws a redirect on success, but my try catch around it was handling it as if it was an error instead of rethrowing it. It's working now in 2.4.8.

**Comment by kettanaito** [comment]
Awesome! 🎉 Good job on figuring that out. Meanwhile, the fix is about ready. Will publish today.

**Comment by kettanaito** [comment]
## Released: v2.4.9 🎉

This has been released in v2.4.9!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.4.9)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.4.9)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by hugotiburtino** [comment]
I'm still having the error `TypeError: Cannot set property headers of [object Response] which has only a getter`
See https://github.com/serlo/cloudflare-worker/pull/882

To reproduce, just clone the [repo](https://github.com/serlo/cloudflare-worker), check the branch `dependabot/npm_and_yarn/msw-2.4.9` out, install with `yarn` and run` yarn test`
