### ISSUE TITLE
MSW + React + Vite: Failed to HMR Update if MSW active

### ISSUE THREAD

**Issue by rizaldirnm** [kettanaito/msw#2401]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/rizaldirnm/msw-vite

### Reproduction steps

```
clone repo: https://github.com/rizaldirnm/msw-vite

yarn install

yarn dev
```

### Current behavior

1. Some how MSW mocking request in asset `react.svg`
![CleanShot 2024-12-24 at 12 18 19@2x](https://github.com/user-attachments/assets/559417aa-2432-42e6-9476-04ebc2fb3943)

2. If we try change something in app, HMR failed to deliver asset because MSW mocked the request
![CleanShot 2024-12-24 at 12 29 55@2x](https://github.com/user-attachments/assets/1450c1bd-c1ba-4ea9-8c77-df335cde1782)

### Expected behavior

MSW should mock only registered handler.

**Comment by shanereid** [comment]
+1

I'm getting the exact same error on a pretty fresh install.
- I'm on macOS
- Happens on Chrome, but not Safari
- `{ onUnhandledRequest: "bypass" }` does not fix the issue.
- Basically exact error as above, says it hot updates but does not. msw seems to be intercepting hmr requests? (screenshot attached)
- react 18.3.1
- vite 5.4.8
- msw 2.7.0

<img width="1056" alt="Screenshot 2025-01-02 at 22 21 52" src="https://github.com/user-attachments/assets/cf9d2257-6bed-4164-9a6e-293bb568bf35" />

**Comment by charlieforward9** [comment]
May be related, I'm getting:

```
[MSW] Warning: intercepted a request without a matching request handler:

  • GET /node_modules/.pnpm/graphql@16.9.0/node_modules/graphql/language/parser.mjs?v=cffff488

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks
```

Looks like most of them are coming from the `graphql` lib...

**Comment by yeo311** [comment]
I encountered the same issue and identified the cause.

Within msw, the [@bundled-es-modules/cookie](https://github.com/bundled-es-modules/cookie) package is used to parse request cookies.

This package validates cookie names using a regular expression, and when the validation fails, it throws the error mentioned above.
```js
    var cookieNameRegExp = /^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;
```
https://github.com/bundled-es-modules/cookie/blob/7591afcfa0587459a5e579d16e7f48b6c732199d/index-esm.js#L35C5-L35C61


In my case, some of the cookies used by the service included square brackets in its name. `ex) tr[vid]`

Looking at the regular expression, it does not account for square brackets. According to [RFC 6265](https://www.rfc-editor.org/rfc/rfc6265#section-4.1.1), square brackets are not allowed in cookie names.

Since I couldn't remove the problematic cookie, I patched the regular expression using `pnpm patch`.

**Comment by clianor** [comment]
This problem was bothering me.
I removed cookies and this problem was solved.

**Comment by oNo500** [comment]
Same here. 

Browser register + localhost cookies. Clear cookies, works.

**Comment by raky291** [comment]
Oh my God, the problem was the cookies! I even spent a few Premium Requests trying to fix it.

**Comment by dsiguero** [comment]
Removing cookies isn't a fix when using a SSO for login... how can this be still broken?
