### ISSUE TITLE
Request stuck in pending state / promise never resolves

### ISSUE THREAD

**Issue by smeijer** [kettanaito/msw#941]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.35.0   |
| node | 14.17.6     |
| OS   | codesandbox & ubuntu 20.04    |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer()

server.listen({
  onUnhandledRequest: "bypass"
})

stripe.customers.update("customer_id", {
  name: "stephan",
  email: "stephan@example.com"
}).finally(() => {
  // you'll never come here
});
```

## Actual request

```js
stripe.customers.update("customer_id", {
  name: "stephan",
  email: "stephan@example.com"
}).finally(() => {
  // you'll never come here
});
```

## Current behavior

Request is made, Stripe shows that there was a successful response, but the promise never resolves.

## Expected behavior

Request should resolve

## Screenshots

**codesandbox**

https://codesandbox.io/s/spring-dawn-3cht3?file=/pages/api/stripe.js

**terminal**

https://user-images.githubusercontent.com/1196524/137531832-6b5fb6c8-e4f5-4c0d-9a2f-f16f1698f48c.mp4

**Comment by kettanaito** [comment]
Hey, @smeijer. Thanks for reporting this.

I suspect that the way the Stripe client does the request conflicts with `@mswjs/interceptors`, resulting in a pending request. I'll provide you with more details once I have the time to look into this. Thank you for understanding.

**Comment by igor-krupa** [comment]
When I set up `setupWorker` like in [this](https://github.com/mswjs/examples/tree/master/examples/rest-react) example in my app my unhandled requests are not bypassed properly.

I see in Network tab in Dev tools that a request is made and there are no errors however response data is somehow intercepted by msw and returned data is undefined. 

I just use simple fetch and logging output, but all I got is this in console:

```console
Uncaught (in promise) TypeError: Failed to execute 'json' on 'Response': body stream already read
```

If I remove worker everything works fine.

I wanted to prepare a codesandbox but there everything works OK.

I am using React with gatsby.

I am a bit lost. How I can debug this?

--- Edit:
Sorry if this is not a good place to ask this. I just found this by searching "bypass" in issues.

**Comment by kettanaito** [comment]
@igorkrup, I'd recommend you open a [new discussion](https://github.com/mswjs/msw/discussions/new) (Q&A) where we can follow up on this. It may not be related to this issue.

**Comment by kettanaito** [comment]
I'm looking at the request processing and it seems to be resolved on both Stripe and Interceptors sides. Both these parts are reached:

```sh
http POST https://api.stripe.com/v1/customers/customer_id request finished +236ms
http POST https://api.stripe.com/v1/customers/customer_id request ended POST https://api.stripe.com/v1/customers/customer_id +0ms
http POST https://api.stripe.com/v1/customers/customer_id 401 POST https://api.stripe.com/v1/customers/customer_id +100ms
```
> From [ClientRequestOverride](https://github.com/mswjs/interceptors/blob/adc15848cb43e691dacf052792cb386bcad881c3/src/interceptors/ClientRequest/createClientRequestOverride.ts#L302-L305).

And then the related `requestPromise` in `NodeHttpClient` in Stripe is resolved also:

https://github.com/stripe/stripe-node/blob/7dd6c7cf98f8a5fab5d551d70aad4cf2e844d0db/lib/net/NodeHttpClient.js#L58-L60

https://github.com/stripe/stripe-node/blob/7dd6c7cf98f8a5fab5d551d70aad4cf2e844d0db/lib/net/NodeHttpClient.js#L84

If I add logs in the "response" callback and the `requestPromise.then()`, I'll see both of them, indicating that the promise created by `stripe.customers.update` has been successfully resolved. 

The promise in the API route, however, keeps pending. When interceptors are removed, the promise rejects with the following error originating from [res.toJSON()@StripeResource](https://github.com/stripe/stripe-node/blob/7dd6c7cf98f8a5fab5d551d70aad4cf2e844d0db/lib/StripeResource.js#L214):

```sh
[api] stripe error StripeAuthenticationError: Invalid API Key provided: SECRET_KEY
    at res.toJSON.then.StripeAPIError.message (/Users/kettanaito/Projects/contrib/msw-next-api-route/node_modules/stripe/lib/StripeResource.js:214:23)
```

Let's take a look what's passed to that closure when the interceptors are enabled...

**Comment by kettanaito** [comment]
## Root cause

The following `response` listener is the root cause of why the request never resolves:

https://github.com/mswjs/interceptors/blob/adc15848cb43e691dacf052792cb386bcad881c3/src/interceptors/ClientRequest/createClientRequestOverride.ts#L293-L300

It reads the `IncomingMessage` body and, once that's done, any other listeners on `res.on('data')` will never get that event emitted. Here's where Stripe attempts to get the response and parse it to JSON:

https://github.com/stripe/stripe-node/blob/7dd6c7cf98f8a5fab5d551d70aad4cf2e844d0db/lib/net/NodeHttpClient.js#L107-L122

This entire promise never resolves because the `this._res.once('data')` is never called once interceptors extract the response body via `getIncomingMessageBody`. In particular, because this function removes _all_ listeners on the response, including those attached by Stripe:

https://github.com/mswjs/interceptors/blob/adc15848cb43e691dacf052792cb386bcad881c3/src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts#L22

> Removing this line makes the scenario pass. 

That's rather strange, as we clone the incoming message to prevent this very issue from happening.

**Comment by kettanaito** [comment]
I've implemented the fix in https://github.com/mswjs/interceptors/pull/165 but currently experience a regression in one of the tests. Once it's resolved, the fix will be merged. 

It seems I've finally found a way to properly clone the `IncomingMessage` by piping it to a `PassThrough` stream in order to read its "data" twice: for the internal "response" event and for the arbitrary response event listeners that the request client (or developer) may attach.

**Comment by smeijer** [comment]
If I understood correctly, this has been fixed in the dependency. Is there an eta on when a new msw will be published?

**Comment by kettanaito** [comment]
The fix will propagate with the next update of the `@mswjs/interceptors` library. We're currently working on a few bug fixes we'd like to include in that next release. I'd expect it to be released this month.

**Comment by plesiv** [comment]
I just want to note that I'm encountering this issue with `msw` version `0.36.8`. I think this is due to these two:
- `interceptors` being on `0.12.7` (released on Sep 7 2021) for this version of `msw` https://github.com/mswjs/msw/blob/main/package.json#L67 .
- the fix was merged on Nov 1 2021 https://github.com/mswjs/interceptors/pull/165

I'll try to fix.

**Comment by plesiv** [comment]
I tried upgrading `interceptors` to `0.13.2` in `msw` and then building `msw`. The problem still persists after I do this. I'll debug further.

**Comment by kettanaito** [comment]
@plesiv, thanks for updating this. Strange, I've confirmed the issue is gone by using this very example and the new version of the interecptors. We're planning on upgrading it in `msw`, so you may wait for a little before that happens. We can come back to it then.

**Comment by 95th** [comment]
Hi. I am facing this same issue in my node integration tests - where if I turn off the msw server, the test completes fine. But get stuck when the mocking is on. any way to debug this?

**Comment by 95th** [comment]
I am using chai HTTP module in the tests and I see there is some history with superAgent. Is there still open issue with using superagent?

**Comment by 95th** [comment]
With `DEBUG=*`, I see the following as the last thing in the logs for the stuck request:
```
http PUT https://mysite.com/foo?component_id=bar chunk successfully stored! [
  <Buffer .....>
] +0ms
  http PUT https://mysite.com/foo?component_id=bar event:socket +1ms
```

**Comment by 95th** [comment]
Also, there seems to be no difference if I have the handler for this route or not, it just gets stuck regardless.
